### PR TITLE
python3 and wx update

### PR DESCRIPTION
**Pull request by ZirconCode**

### CODE REVIEW

**Comment by ZirconCode** [comment]
nevermind everything is broken, will spend some time later

**Comment by collingreen** [comment]
Hey, thanks for getting involved! These libs are pretty hard to get working these days, as you have seen! I struggled even getting everything installed, let alone working. I appreciate you taking some of this on - if you manage to get it working that is lovely. If not, though, don't stress - my eventual plan is to re-build everything using more modern and accessible UI tooling.

**Comment by ZirconCode** [comment]
Haha yeah I noticed, I thought it was a small thing. Chronolapse has some nostalgic value for me and it used to be the thing for ludum dare, and there don't seem to be any alternatives without similar troubles currently. What I did this time around was (from inside the correct directory):
`watch -n 5 scrot '%Y-%m-%d-%s_screenshot_$wx$h.jpg' -e 'mv $f ~/ludumdare45/screenies'`

I think a rebuild is probably the best solution. Currently quite busy but if I find time, this is on my list ;) Thanks for writing this tool so many years ago!

**Comment by collingreen** [comment]
Jealousy over people that had scrot (while I was on windows) was the impetus for creating CL in the first place! That, plus needing a reminder to post for LD. :)

**Pull request closed without merging**
